### ISSUE TITLE
error

### ISSUE THREAD

**Issue by marcelowu** [vuefront/opencart#2]
http://opencart.local/index.php?route=extension/module/d_vuefront/graphql

{"errors":[{"message":"Syntax Error GraphQL (1:1) Unexpected <EOF>\n\n1: \n   ^\n","category":"graphql","locations":[{"line":1,"column":1}]}]}

http://localhost:3000/

NuxtServerError
Network error: only absolute urls are supported

**Comment by anaymalpani** [comment]
how you solved the error

facing same error
