### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by mrinc** [vuefront/opencart#28]
Create a new release of this plugin.

The last release was 2019 and it's breaking things.

Ref: https://github.com/vuefront/opencart/issues/25 https://github.com/vuefront/vuefront/issues/36

**Comment by mrinc** [comment]
For anyone having issues with vuefront and opencart, just download the master branch: [https://github.com/vuefront/opencart/archive/master.zip](https://github.com/vuefront/opencart/archive/master.zip )

Install that as the plugin by just copying the files onto your server.

**Comment by isuke01** [comment]
Hey, I actually did it, and still this issue, I saw this issue is been here for some long time. 
Is this project dead?

**Comment by mrinc** [comment]
Think so ...
