### ISSUE TITLE
how you solved the error

### ISSUE THREAD

**Issue by anaymalpani** [vuefront/opencart#3]
how you solved the error

facing same error

_Originally posted by @anaymalpani in https://github.com/vuefront/opencart/issues/2#issuecomment-538425164_

{"errors":[{"message":"Syntax Error GraphQL (1:1) Unexpected <EOF>\n\n1: \n   ^\n","category":"graphql","locations":[{"line":1,"column":1}]}]}

**Comment by dmitriyzhuk** [comment]
please try the latest release 1.1.0

**Comment by anaymalpani** [comment]
yes but still having some issue but good one to start with.

thanks a lot
