### ISSUE TITLE
Can't find VueFront in Modules

### ISSUE THREAD

**Issue by raydvard** [vuefront/opencart#4]
After Uploading via Extension Installer VueFront is not showing up in the 
**Admin Panel -> Extensions -> Extensions -> Modules**

Opencart Version :
**3.0.3.2**

VueFront Version / File : 
**v1.1.0 (d_vuefront_compiled_oc3.0.3.1.v1.1.0.ocmod.zip)**

I also have tried refreshing from 
**Admin Panel -> Extensions -> Modifications**

**Comment by dmitriyzhuk** [comment]
please try again with version v1.1.1
