### ISSUE TITLE
Support for Journal Theme or custom themes?

### ISSUE THREAD

**Issue by mfadel85** [vuefront/opencart#5]
Thanks for you work,
Can this extension support special themes?

Best Wishes

**Comment by dmitriyzhuk** [comment]
Hi, this is a SPA Web App. it is built completely on VueJS and Nuxt and fully replaces the Frontend of your OpenCart site.

This means if you have any theme - it will be replaced. So it doesn't matter if you have Journal installed. VueFront will ignore it. 

All the themes are created using all technology stacks. Journal is one of them. With VueFront you get to migrate to the new TechStack with a SPA, GraphQL, PWA and more.
